### ISSUE TITLE
Error when symlinking into a non-existent directory

### ISSUE THREAD

**Issue by ben-z** [ben-z/dot-conf#2]
```
(dot-conf) ben@wato-wato3:~/Projects/git-conf$ vi git-subrepo/lib/git-subrepo
git-subrepo    git-subrepo.d/
(dot-conf) ben@wato-wato3:~/Projects/git-conf$ vi git-subrepo/lib/git-subrepo
(dot-conf) ben@wato-wato3:~/Projects/git-conf$ python -m dc .conf.yaml
Applying config (ALL): /home/ben/Projects/git-conf/.conf.yaml
Backing up /home/ben/.gitconfig to /home/ben/.config/dot-conf/backup/.gitconfig.1587789182.0238035.bak
Linking /home/ben/Projects/git-conf/gitconfig -> /home/ben/.gitconfig
Linking /home/ben/Projects/git-conf/git-subrepo -> /home/ben/.config/git/git-subrepo
Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/dot-conf/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ben/miniconda3/envs/dot-conf/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ben/miniconda3/envs/dot-conf/lib/python3.8/site-packages/dot_conf-0.0.3-py3.8.egg/dc/__main__.py", line 53, in <module>
  File "/home/ben/miniconda3/envs/dot-conf/lib/python3.8/site-packages/dot_conf-0.0.3-py3.8.egg/dc/__main__.py", line 37, in main
  File "/home/ben/miniconda3/envs/dot-conf/lib/python3.8/site-packages/dot_conf-0.0.3-py3.8.egg/dc/dcconfig.py", line 58, in apply
  File "/home/ben/miniconda3/envs/dot-conf/lib/python3.8/site-packages/dot_conf-0.0.3-py3.8.egg/dc/dcconfig.py", line 63, in apply_user_symlinks
  File "/home/ben/miniconda3/envs/dot-conf/lib/python3.8/site-packages/dot_conf-0.0.3-py3.8.egg/dc/dcconfig.py", line 87, in _apply_symlinks
  File "/home/ben/miniconda3/envs/dot-conf/lib/python3.8/pathlib.py", line 1374, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/home/ben/miniconda3/envs/dot-conf/lib/python3.8/pathlib.py", line 442, in symlink
    return os.symlink(a, b)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ben/Projects/git-conf/git-subrepo' -> '/home/ben/.config/git/git-subrepo'
```

Need to ensure the parent directory of the symlink exists before linking.

**Comment by ben-z** [comment]
Closing as fixed on the current default branch. The Rust implementation now creates each destination parent directory before linking (via fs::create_dir_all in src/lib.rs), so symlinking into a previously missing directory no longer fails with ENOENT. This is also covered by the nested destination test in tests/dot_conf_test.rs.
